const express = require('express');
// ...existing code...
const roleRoutes = require('./routes/roleRoutes');

// ...existing code...
// Add this line after your other route configurations
app.use('/api/roles', roleRoutes);
// ...existing code...