import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { QueryProvider } from "@/providers/query-provider"; // ✅ Query Provider
import { AuthProvider } from "@/providers/session-provider"; // ✅ Import Auth Provider
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider> {/* ✅ Wrap in AuthProvider */}
          <QueryProvider> {/* ✅ Wrap inside QueryProvider */}
            {children}
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
